### ISSUE TITLE
Box name not working

### ISSUE THREAD

**Issue by pwmcintyre** [phips/splunkbox#2]
you box name of `centos7` doesn't work for me, should this instead be `centos/7`?

Link to line:
https://github.com/phips/splunkbox/blob/jldemo/Vagrantfile#L7

```
$ vagrant up
Bringing machine 'head' up with 'virtualbox' provider...
Bringing machine 'fwd1' up with 'virtualbox' provider...
Bringing machine 'fwd2' up with 'virtualbox' provider...
==> head: Box 'centos7' could not be found. Attempting to find and install...
    head: Box Provider: virtualbox
    head: Box Version: >= 0
==> head: Box file was not detected as metadata. Adding it directly...
==> head: Adding box 'centos7' (v0) for provider: virtualbox
    head: Downloading: centos7
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/pwmcintyre/git/splunkbox/centos7
```

**Comment by phips** [comment]
Hello @pwmcintyre. You need to have added a box and called it that. See the vagrant documentation here: https://www.vagrantup.com/docs/cli/box.html

**Comment by pwmcintyre** [comment]
Ultimately it's your call, but if you put a / in there it'll work out-of-the-box

**Comment by phips** [comment]
That's probably because you're pulling from a default box repository, I am not. That's just a label, nothing more. I have locally created boxes with that label, and I don't want something pulling from a remote repository.
